import {Router} from "express";import bcrypt from "bcryptjs";import jwt from "jsonwebtoken";import crypto from "node:crypto";import {OAuth2Client} from "google-auth-library";import {z} from "zod";import {User} from "../models/index.js";import {auth,AuthRequest} from "../middleware/auth.js";
const router=Router();const body=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(8).regex(/[A-Z]/).regex(/[0-9]/),photo:z.string().url().optional().or(z.literal("")),role:z.enum(["supporter","creator"])});
const tokenFor=(u:any)=>jwt.sign({id:u._id,email:u.email,role:u.role,name:u.name},process.env.JWT_SECRET!,{expiresIn:"7d"});
router.post("/register",async(req,res,next)=>{try{const input=body.parse(req.body);if(await User.exists({email:input.email}))return res.status(409).json({message:"An account already exists with this email"});const user=await User.create({...input,password:await bcrypt.hash(input.password,12),credits:input.role==="supporter"?50:20});res.status(201).json({token:tokenFor(user),user:{_id:user._id,name:user.name,email:user.email,photo:user.photo,role:user.role,credits:user.credits}})}catch(e){next(e)}});
router.post("/login",async(req,res,next)=>{try{const user=await User.findOne({email:req.body.email}).select("+password");if(!user||!await bcrypt.compare(req.body.password,user.password))return res.status(401).json({message:"Incorrect email or password"});res.json({token:tokenFor(user),user:{_id:user._id,name:user.name,email:user.email,photo:user.photo,role:user.role,credits:user.credits}})}catch(e){next(e)}});
router.post("/google",async(req,res,next)=>{try{if(!process.env.GOOGLE_CLIENT_ID)return res.status(503).json({message:"Google Sign-In is not configured"});const ticket=await new OAuth2Client(process.env.GOOGLE_CLIENT_ID).verifyIdToken({idToken:req.body.credential,audience:process.env.GOOGLE_CLIENT_ID});const profile=ticket.getPayload();if(!profile?.email||!profile.name)return res.status(401).json({message:"Google account could not be verified"});let user=await User.findOne({email:profile.email});if(!user)user=await User.create({name:profile.name,email:profile.email,photo:profile.picture,password:await bcrypt.hash(crypto.randomUUID(),12),role:req.body.role==="creator"?"creator":"supporter",credits:req.body.role==="creator"?20:50});res.json({token:tokenFor(user),user:{_id:user._id,name:user.name,email:user.email,photo:user.photo,role:user.role,credits:user.credits}})}catch(e){next(e)}});
router.get("/me",auth,async(req:AuthRequest,res)=>{const user=await User.findById(req.user!.id).select("-password");res.json({user})});
router.patch("/me",auth,async(req:AuthRequest,res)=>{const updates:{name?:string;photo?:string}={};if(typeof req.body.name==="string"&&req.body.name.trim().length>1)updates.name=req.body.name.trim();if(typeof req.body.photo==="string")updates.photo=req.body.photo;const user=await User.findByIdAndUpdate(req.user!.id,updates,{new:true}).select("-password");res.json({user})});
export default router;
