import {Router} from "express";import {Campaign,Contribution,Notification,Report,User} from "../models/index.js";import {allow,auth,AuthRequest} from "../middleware/auth.js";
const router=Router();router.get("/",async(req,res)=>{const filter:any={};if(req.query.status)filter.status=req.query.status;if(req.query.category)filter.category=req.query.category;if(req.query.search)filter.$text={$search:req.query.search};res.json(await Campaign.find(filter).sort({raised:-1}).limit(Math.min(Number(req.query.limit)||50,100)))});
router.get("/:id",async(req,res)=>{const item=await Campaign.findById(req.params.id);item?res.json(item):res.status(404).json({message:"Campaign not found"})});
router.post("/",auth,allow("creator"),async(req:AuthRequest,res)=>res.status(201).json(await Campaign.create({...req.body,creatorName:req.user!.name,creatorEmail:req.user!.email,status:"pending"})));
router.patch("/:id",auth,async(req:AuthRequest,res)=>{const item=await Campaign.findById(req.params.id);if(!item)return res.status(404).json({message:"Campaign not found"});if(req.user!.role!=="admin"&&item.creatorEmail!==req.user!.email)return res.status(403).json({message:"Not allowed"});const safe=req.user!.role==="admin"?req.body:(({title,story,reward})=>({title,story,reward}))(req.body);Object.assign(item,safe);await item.save();res.json(item)});
router.delete("/:id",auth,async(req:AuthRequest,res)=>{const item=await Campaign.findById(req.params.id);if(!item)return res.status(404).json({message:"Campaign not found"});if(req.user!.role!=="admin"&&item.creatorEmail!==req.user!.email)return res.status(403).json({message:"Not allowed"});const approved=await Contribution.find({campaignId:item._id,status:"approved"});await Promise.all(approved.map(c=>User.updateOne({email:c.supporterEmail},{$inc:{credits:c.amount}})));await Contribution.deleteMany({campaignId:item._id});await item.deleteOne();res.json({message:"Campaign deleted and approved contributions refunded"})});
router.post("/:id/report",auth,allow("supporter"),async(req:AuthRequest,res)=>{const c=await Campaign.findById(req.params.id);if(!c)return res.status(404).json({message:"Campaign not found"});res.status(201).json(await Report.create({campaignId:c._id,campaignTitle:c.title,reporterName:req.user!.name,reporterEmail:req.user!.email,reason:req.body.reason}))});
router.patch("/:id/review",auth,allow("admin"),async(req:AuthRequest,res)=>{const c=await Campaign.findByIdAndUpdate(req.params.id,{status:req.body.status},{new:true});if(c)await Notification.create({toEmail:c.creatorEmail,message:`Your campaign "${c.title}" was ${req.body.status}.`,actionRoute:"/dashboard"});res.json(c)});
export default router;
