import { Campaign } from "./types";
export const campaigns: Campaign[] = [
 { _id:"solar-water",title:"Solar water for Char Kukri",story:"A community-owned solar pumping system will bring safe water to 600 coastal families while creating local maintenance jobs.",category:"Community",goal:120000,minimumContribution:20,deadline:"2026-12-20",reward:"Field notes and a name on the community wall",image:"https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1200&q=80",raised:87420,creatorName:"Nadia Rahman",creatorEmail:"nadia@fundora.demo",status:"approved"},
 { _id:"braille-reader",title:"Pocket Braille Reader",story:"An affordable open-source reader that turns digital text into refreshable Braille for students across Bangladesh.",category:"Technology",goal:95000,minimumContribution:25,deadline:"2026-11-15",reward:"Early-access build updates",image:"https://images.unsplash.com/photo-1559757175-0eb30cd8c063?auto=format&fit=crop&w=1200&q=80",raised:69210,creatorName:"Arian Kabir",creatorEmail:"arian@fundora.demo",status:"approved"},
 { _id:"pottery-studio",title:"Rebuild Shila's Pottery Studio",story:"Restore a flood-damaged artisan studio and train twelve young makers in traditional terracotta craft.",category:"Art",goal:60000,minimumContribution:10,deadline:"2026-10-28",reward:"Handmade postcard from the studio",image:"https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1200&q=80",raised:51340,creatorName:"Shila Rani",creatorEmail:"shila@fundora.demo",status:"approved"},
 { _id:"mobile-clinic",title:"Mobile Clinic for Tea Gardens",story:"Equip a weekly mobile clinic with diagnostics, maternal care supplies and telemedicine access.",category:"Health",goal:180000,minimumContribution:50,deadline:"2027-01-30",reward:"Quarterly impact report",image:"https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80",raised:118900,creatorName:"Dr. Farhana Islam",creatorEmail:"farhana@fundora.demo",status:"approved"},
 { _id:"river-library",title:"The Floating River Library",story:"Turn a wooden boat into a solar-powered library serving children in hard-to-reach river islands.",category:"Education",goal:80000,minimumContribution:15,deadline:"2026-09-25",reward:"Digital founding supporter badge",image:"https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1200&q=80",raised:44070,creatorName:"Rafi Ahmed",creatorEmail:"rafi@fundora.demo",status:"approved"},
 { _id:"jute-packaging",title:"Jute Packaging, Reimagined",story:"Pilot compostable jute packaging that helps small retailers replace single-use plastic.",category:"Environment",goal:140000,minimumContribution:30,deadline:"2026-12-05",reward:"Sample kit for qualifying supporters",image:"https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1200&q=80",raised:93200,creatorName:"Tasmia Noor",creatorEmail:"tasmia@fundora.demo",status:"approved"}
];
export const testimonials = [
 {name:"Mahin Chowdhury",role:"Supporter",quote:"I can see exactly where each credit goes. The updates make supporting a project feel personal.",photo:"https://i.pravatar.cc/160?img=12"},
 {name:"Sadia Karim",role:"Creator",quote:"Fundora gave our small idea a credible home and a community that believed in the first prototype.",photo:"https://i.pravatar.cc/160?img=47"},
 {name:"Rashed Alam",role:"Supporter",quote:"The clear milestones and local focus make this the easiest way to back meaningful work.",photo:"https://i.pravatar.cc/160?img=14"}
];
